export const POLICIES = {
  USER_VIEW_ALL: "USER_VIEW_ALL",
  USER_VIEW_SELF: "USER_VIEW_SELF",
  USER_CREATE: "USER_CREATE",
  USER_EDIT: "USER_EDIT",
  USER_DELETE: "USER_DELETE",
  ////WISHLIST
  USER_BOOKS_WISHLIST_VIEW_SELF: "USER_BOOKS_WISHLIST_VIEW_SELF",
  USER_BOOKS_WISHLIST_VIEW_ALL: "USER_BOOKS_WISHLIST_VIEW_ALL",
  USER_BOOKS_WISHLIST_ADD: "USER_BOOKS_WISHLIST_ADD",
  USER_BOOKS_WISHLIST_REMOVE: "USER_BOOKS_WISHLIST_REMOVE",
  USER_BOOKS_WISHLIST_EDIT: "USER_BOOKS_WISHLIST_EDIT",
  ////CART
  USER_BOOKS_CART_VIEW_SELF: "USER_BOOKS_CART_VIEW_SELF",
  USER_BOOKS_CART_VIEW_ALL: "USER_BOOKS_CART_VIEW_ALL",
  USER_BOOKS_CART_ADD: "USER_BOOKS_CART_ADD",
  USER_BOOKS_CART_REMOVE: "USER_BOOKS_CART_REMOVE",
  USER_BOOKS_CART_EDIT: "USER_BOOKS_CART_EDIT",
  ////BILL
  USER_HOADON_VIEW_SELF: "USER_HOADON_VIEW_SELF",
  USER_HOADON_VIEW_ALL: "USER_HOADON_VIEW_ALL",
  USER_HOADON_ADD: "USER_HOADON_ADD",
  USER_HOADON_REMOVE: "USER_HOADON_REMOVE",
  USER_HOADON_EDIT: "USER_HOADON_EDIT",
};