export const POLICIES = {
  USER_VIEW_ALL: "USER_VIEW_ALL",
  USER_VIEW_SELF: "USER_VIEW_SELF",
  USER_CREATE: "USER_CREATE",
  USER_EDIT: "USER_EDIT",
  USER_DELETE: "USER_DELETE",
  USER_BOOKS_WISHLIST_VIEW_SELF: "USER_BOOKS_WISHLIST_VIEW_SELF",
  USER_BOOKS_WISHLIST_VIEW_ALL: "USER_BOOKS_WISHLIST_VIEW_ALL",
  USER_BOOKS_WISHLIST_ADD: "USER_BOOKS_WISHLIST_ADD",
  USER_BOOKS_WISHLIST_REMOVE: "USER_BOOKS_WISHLIST_REMOVE",
  USER_BOOKS_WISHLIST_EDIT: "USER_BOOKS_WISHLIST_EDIT",
};