import { POLICIES  } from "../utils/constants/policies.js";

export const ROLE_POLICY_MAP = {
  ADMIN: [
    POLICIES.USER_VIEW_ALL,
    POLICIES.USER_VIEW_SELF,
    POLICIES.USER_CREATE,
    POLICIES.USER_EDIT,
    POLICIES.USER_DELETE,
    POLICIES.USER_BOOKS_WISHLIST_VIEW_ALL,
    POLICIES.USER_BOOKS_WISHLIST_VIEW_SELF,
    POLICIES.USER_BOOKS_WISHLIST_ADD,
    POLICIES.USER_BOOKS_WISHLIST_REMOVE,
    POLICIES.USER_BOOKS_WISHLIST_EDIT,
  ],
  USER: [
    POLICIES.USER_VIEW_SELF,
    POLICIES.USER_EDIT,
    POLICIES.USER_BOOKS_WISHLIST_VIEW_SELF,
    POLICIES.USER_BOOKS_WISHLIST_ADD,
    POLICIES.USER_BOOKS_WISHLIST_REMOVE,
  ],
};