import { POLICIES  } from "../utils/constants/policies.js";

export const ROLE_POLICY_MAP = {
  ADMIN: [
    ////USER
    POLICIES.USER_VIEW_ALL,
    POLICIES.USER_VIEW_SELF,
    POLICIES.USER_CREATE,
    POLICIES.USER_EDIT,
    POLICIES.USER_DELETE,
    ////WISHLIST
    POLICIES.USER_BOOKS_WISHLIST_VIEW_ALL,
    POLICIES.USER_BOOKS_WISHLIST_VIEW_SELF,
    POLICIES.USER_BOOKS_WISHLIST_ADD,
    POLICIES.USER_BOOKS_WISHLIST_REMOVE,
    POLICIES.USER_BOOKS_WISHLIST_EDIT,
    ////CART
    POLICIES.USER_BOOKS_CART_VIEW_ALL,
    POLICIES.USER_BOOKS_CART_VIEW_SELF,
    POLICIES.USER_BOOKS_CART_ADD,
    POLICIES.USER_BOOKS_CART_REMOVE,
    POLICIES.USER_BOOKS_CART_EDIT,
    ////BILL
    POLICIES.USER_HOADON_VIEW_ALL,
    POLICIES.USER_HOADON_VIEW_SELF,
    POLICIES.USER_HOADON_ADD,
    POLICIES.USER_HOADON_REMOVE,
    POLICIES.USER_HOADON_EDIT,
  ],
  USER: [
    ////USER
    POLICIES.USER_VIEW_SELF,
    POLICIES.USER_EDIT,
    ////WISHLIST
    POLICIES.USER_BOOKS_WISHLIST_VIEW_SELF,
    POLICIES.USER_BOOKS_WISHLIST_ADD,
    POLICIES.USER_BOOKS_WISHLIST_REMOVE,
    ////CART
    POLICIES.USER_BOOKS_CART_VIEW_SELF,
    POLICIES.USER_BOOKS_CART_ADD,
    POLICIES.USER_BOOKS_CART_EDIT,
    POLICIES.USER_BOOKS_CART_REMOVE,
    ////BILL
    POLICIES.USER_HOADON_VIEW_SELF,
    POLICIES.USER_HOADON_ADD,
    POLICIES.USER_HOADON_EDIT,
    POLICIES.USER_HOADON_REMOVE,
  ],
};